// <auto-generated />
namespace UsersDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LastNameField_Change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastNameField_Change));
        
        string IMigrationMetadata.Id
        {
            get { return "201705101430131_LastNameField_Change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
